/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando
 */
public class administrador extends javax.swing.JFrame {

    static ArrayList<libros> libros = new ArrayList();
    /**
     * Creates new form administrador
     */
    public administrador() {
        initComponents();
    }
    public ArrayList<libros> getLista (){
        return libros;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ranking = new javax.swing.ButtonGroup();
        genre = new javax.swing.ButtonGroup();
        salir = new javax.swing.JToggleButton();
        title = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        punc = new javax.swing.JLabel();
        RB_1 = new javax.swing.JRadioButton();
        RB_2 = new javax.swing.JRadioButton();
        RB_3 = new javax.swing.JRadioButton();
        RB_4 = new javax.swing.JRadioButton();
        RB_5 = new javax.swing.JRadioButton();
        cantidad = new javax.swing.JLabel();
        genero = new javax.swing.JLabel();
        RB_6 = new javax.swing.JRadioButton();
        RB_7 = new javax.swing.JRadioButton();
        RB_8 = new javax.swing.JRadioButton();
        RB_9 = new javax.swing.JRadioButton();
        value = new javax.swing.JLabel();
        edicion = new javax.swing.JLabel();
        autor = new javax.swing.JLabel();
        año = new javax.swing.JLabel();
        E1 = new javax.swing.JTextField();
        E2 = new javax.swing.JTextField();
        E3 = new javax.swing.JTextField();
        E4 = new javax.swing.JTextField();
        E5 = new javax.swing.JTextField();
        E6 = new javax.swing.JTextField();
        E7 = new javax.swing.JTextField();
        books = new javax.swing.JScrollPane();
        lista = new javax.swing.JTextArea();
        Agg = new javax.swing.JToggleButton();
        Rep = new javax.swing.JToggleButton();
        delete = new javax.swing.JToggleButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(255, 255, 0));
        salir.setForeground(new java.awt.Color(0, 0, 0));
        salir.setText("Menu Principal");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        title.setForeground(new java.awt.Color(255, 255, 0));
        title.setText("Titulo:");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        desc.setForeground(new java.awt.Color(255, 255, 0));
        desc.setText("descripcion:");
        getContentPane().add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, -1));

        punc.setForeground(new java.awt.Color(255, 255, 0));
        punc.setText("puntuacion:");
        getContentPane().add(punc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        RB_1.setBackground(new java.awt.Color(0, 0, 0));
        ranking.add(RB_1);
        RB_1.setForeground(new java.awt.Color(255, 255, 0));
        RB_1.setText("1");
        RB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_1ActionPerformed(evt);
            }
        });
        getContentPane().add(RB_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        RB_2.setBackground(new java.awt.Color(0, 0, 0));
        ranking.add(RB_2);
        RB_2.setForeground(new java.awt.Color(255, 255, 0));
        RB_2.setText("2");
        getContentPane().add(RB_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        RB_3.setBackground(new java.awt.Color(0, 0, 0));
        ranking.add(RB_3);
        RB_3.setForeground(new java.awt.Color(255, 255, 0));
        RB_3.setText("3");
        getContentPane().add(RB_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        RB_4.setBackground(new java.awt.Color(0, 0, 0));
        ranking.add(RB_4);
        RB_4.setForeground(new java.awt.Color(255, 255, 0));
        RB_4.setText("4");
        getContentPane().add(RB_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        RB_5.setBackground(new java.awt.Color(0, 0, 0));
        ranking.add(RB_5);
        RB_5.setForeground(new java.awt.Color(255, 255, 0));
        RB_5.setSelected(true);
        RB_5.setText("5");
        RB_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_5ActionPerformed(evt);
            }
        });
        getContentPane().add(RB_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        cantidad.setForeground(new java.awt.Color(255, 255, 0));
        cantidad.setText("disponibles:");
        cantidad.setToolTipText("");
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        genero.setForeground(new java.awt.Color(255, 255, 0));
        genero.setText("Genero:");
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        RB_6.setBackground(new java.awt.Color(0, 0, 0));
        genre.add(RB_6);
        RB_6.setForeground(new java.awt.Color(255, 255, 0));
        RB_6.setText("Fantasia");
        getContentPane().add(RB_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        RB_7.setBackground(new java.awt.Color(0, 0, 0));
        genre.add(RB_7);
        RB_7.setForeground(new java.awt.Color(255, 255, 0));
        RB_7.setSelected(true);
        RB_7.setText("Romance");
        getContentPane().add(RB_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        RB_8.setBackground(new java.awt.Color(0, 0, 0));
        genre.add(RB_8);
        RB_8.setForeground(new java.awt.Color(255, 255, 0));
        RB_8.setText("Accion");
        getContentPane().add(RB_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        RB_9.setBackground(new java.awt.Color(0, 0, 0));
        genre.add(RB_9);
        RB_9.setForeground(new java.awt.Color(255, 255, 0));
        RB_9.setText("Historia");
        getContentPane().add(RB_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        value.setForeground(new java.awt.Color(255, 255, 0));
        value.setText("Valor: LPS.");
        getContentPane().add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        edicion.setForeground(new java.awt.Color(255, 255, 0));
        edicion.setText("edicion:");
        getContentPane().add(edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        autor.setForeground(new java.awt.Color(255, 255, 0));
        autor.setText("autor:");
        getContentPane().add(autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        año.setForeground(new java.awt.Color(255, 255, 0));
        año.setText("año:");
        año.setToolTipText("");
        getContentPane().add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        E1.setBackground(new java.awt.Color(255, 255, 0));
        E1.setForeground(new java.awt.Color(0, 0, 0));
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 220, -1));

        E2.setBackground(new java.awt.Color(255, 255, 0));
        E2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 190, -1));

        E3.setBackground(new java.awt.Color(255, 255, 0));
        E3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, -1));

        E4.setBackground(new java.awt.Color(255, 255, 0));
        E4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 190, -1));

        E5.setBackground(new java.awt.Color(255, 255, 0));
        E5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 210, -1));

        E6.setBackground(new java.awt.Color(255, 255, 0));
        E6.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 220, -1));

        E7.setBackground(new java.awt.Color(255, 255, 0));
        E7.setForeground(new java.awt.Color(0, 0, 0));
        E7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E7ActionPerformed(evt);
            }
        });
        getContentPane().add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 220, -1));

        lista.setBackground(new java.awt.Color(255, 255, 0));
        lista.setColumns(20);
        lista.setForeground(new java.awt.Color(0, 0, 0));
        lista.setRows(5);
        books.setViewportView(lista);

        getContentPane().add(books, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 240, 370));

        Agg.setBackground(new java.awt.Color(255, 255, 0));
        Agg.setForeground(new java.awt.Color(0, 0, 0));
        Agg.setText("Añadir");
        Agg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AggMouseClicked(evt);
            }
        });
        getContentPane().add(Agg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        Rep.setBackground(new java.awt.Color(255, 255, 0));
        Rep.setForeground(new java.awt.Color(0, 0, 0));
        Rep.setText("Listar");
        Rep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepMouseClicked(evt);
            }
        });
        getContentPane().add(Rep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        delete.setBackground(new java.awt.Color(255, 255, 0));
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("Eliminar libro");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/color_negro.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        Main M = new Main();
        M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirMouseClicked

    private void RB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_1ActionPerformed

    private void RB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_5ActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E1ActionPerformed

    private void E7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E7ActionPerformed

    private void AggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AggMouseClicked
        // TODO add your handling code here:
        libros L = new libros();
        String nombre = E1.getText();
        L.setTitulo(nombre);
        String descripcion = E2.getText();
        L.setDescripcion(descripcion);
        if (RB_1.isSelected()){
            L.setPuntuacion(1);
        }
        if (RB_2.isSelected()){
            L.setPuntuacion(2);
        }
        if (RB_3.isSelected()){
            L.setPuntuacion(3);
        }
        if (RB_4.isSelected()){
            L.setPuntuacion(4);
        }
        if (RB_5.isSelected()){
            L.setPuntuacion(5);
        }
        int disponible = Integer.parseInt(E3.getText());
        L.setDisponible(disponible);
        String genero1="";
        if (RB_6.isSelected()){
            L.setGenero("Fantasia");
        }
        if (RB_7.isSelected()){
            L.setGenero("Romance");
        }
        if (RB_8.isSelected()){
            L.setGenero("Accion");
        }
        if (RB_9.isSelected()){
            L.setGenero("Historia");
        }
        int valor = Integer.parseInt(E4.getText());
        L.setValor(valor);
        String edicion1 = E5.getText();
        L.setEdicion(edicion1);
        String autor1 = E6.getText();
        L.setAutor(autor1);
        String year = E7.getText();
        L.setPublicacion(year);
        libros.add(L);
        E1.setText("");
        E2.setText("");
        E3.setText("");
        E4.setText("");
        E5.setText("");
        E6.setText("");
        E7.setText("");
    }//GEN-LAST:event_AggMouseClicked

    private void RepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepMouseClicked
        // TODO add your handling code here:
        String n ="";
        for (int i = 0; i < libros.size(); i++) {
            n += i+" - "+libros.get(i)+"\n";
        }
        lista.setText(n);
    }//GEN-LAST:event_RepMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        int p = Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese posicion a eliminar"));
        libros.remove(p);
    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Agg;
    private javax.swing.JTextField E1;
    private javax.swing.JTextField E2;
    private javax.swing.JTextField E3;
    private javax.swing.JTextField E4;
    private javax.swing.JTextField E5;
    private javax.swing.JTextField E6;
    private javax.swing.JTextField E7;
    private javax.swing.JLabel Fondo;
    private javax.swing.JRadioButton RB_1;
    private javax.swing.JRadioButton RB_2;
    private javax.swing.JRadioButton RB_3;
    private javax.swing.JRadioButton RB_4;
    private javax.swing.JRadioButton RB_5;
    private javax.swing.JRadioButton RB_6;
    private javax.swing.JRadioButton RB_7;
    private javax.swing.JRadioButton RB_8;
    private javax.swing.JRadioButton RB_9;
    private javax.swing.JToggleButton Rep;
    private javax.swing.JLabel autor;
    private javax.swing.JLabel año;
    private javax.swing.JScrollPane books;
    private javax.swing.JLabel cantidad;
    private javax.swing.JToggleButton delete;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel edicion;
    private javax.swing.JLabel genero;
    private javax.swing.ButtonGroup genre;
    private javax.swing.JTextArea lista;
    private javax.swing.JLabel punc;
    private javax.swing.ButtonGroup ranking;
    private javax.swing.JToggleButton salir;
    private javax.swing.JLabel title;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
}
