/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando
 */
public class Main extends javax.swing.JFrame {

    ArrayList<usuarios> users = new ArrayList();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo_usuario = new javax.swing.ButtonGroup();
        admin = new javax.swing.JRadioButton();
        user = new javax.swing.JRadioButton();
        n_usuario = new javax.swing.JTextField();
        cont = new javax.swing.JTextField();
        user_label = new javax.swing.JLabel();
        pass_lable = new javax.swing.JLabel();
        Login = new javax.swing.JToggleButton();
        create = new javax.swing.JToggleButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tipo_usuario.add(admin);
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setSelected(true);
        admin.setText("admin");
        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        Tipo_usuario.add(user);
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("usuario comun");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        n_usuario.setBackground(new java.awt.Color(255, 255, 255));
        n_usuario.setForeground(new java.awt.Color(0, 0, 0));
        n_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(n_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 150, -1));

        cont.setBackground(new java.awt.Color(255, 255, 255));
        cont.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        user_label.setForeground(new java.awt.Color(255, 255, 255));
        user_label.setText("Usuario");
        getContentPane().add(user_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        pass_lable.setForeground(new java.awt.Color(255, 255, 255));
        pass_lable.setText("Contraseña");
        getContentPane().add(pass_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 156, 70, 20));

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setForeground(new java.awt.Color(255, 0, 0));
        Login.setText("Ingresar");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        create.setBackground(new java.awt.Color(255, 255, 255));
        create.setForeground(new java.awt.Color(255, 0, 0));
        create.setText("crear usuario");
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        Fondo.setBackground(new java.awt.Color(255, 0, 0));
        Fondo.setForeground(new java.awt.Color(255, 0, 0));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/527.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_usuarioActionPerformed

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
        String usuario = n_usuario.getText();
        String contra = cont.getText();
        if (usuario.equals("admin")&&contra.equals("1234")&&admin.isSelected()){
            administrador A = new administrador();
            A.setVisible(true);
            this.setVisible(false);
            n_usuario.setText("");
            cont.setText("");
        }
        else{
            if (user.isSelected()){
                boolean m = false;
                for (int i = 0; i < users.size(); i++) {
                    String a = ((usuarios)users.get(i)).getUsuario();
                    String b = ((usuarios)users.get(i)).getContra();
                    if (usuario.equals(a)&&contra.equals(b)){
                        m = true;
                    }
                }
                if (m==true){
                    comun C = new comun();
                    C.setVisible(true);
                    this.setVisible(false);
                    n_usuario.setText("");
                    cont.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(this, "usuario o contraseña incorrectos");
                }
            }
            else{
                n_usuario.setText("");
                cont.setText("");
                JOptionPane.showMessageDialog(this, "usuario o contraseña incorrecta");
            }
        }
    }//GEN-LAST:event_LoginMouseClicked

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        // TODO add your handling code here:
        usuarios U = new usuarios();
        String nombre = JOptionPane.showInputDialog(this,"Ingrese su nombre");
        U.setUsuario(nombre);
        String contrasenha = JOptionPane.showInputDialog(this,"Ingrese su contraseña");
        U.setContra(contrasenha);
        U.setNacimiento(new Date());
        users.add(U);
    }//GEN-LAST:event_createMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JToggleButton Login;
    private javax.swing.ButtonGroup Tipo_usuario;
    private javax.swing.JRadioButton admin;
    private javax.swing.JTextField cont;
    private javax.swing.JToggleButton create;
    private javax.swing.JTextField n_usuario;
    private javax.swing.JLabel pass_lable;
    private javax.swing.JRadioButton user;
    private javax.swing.JLabel user_label;
    // End of variables declaration//GEN-END:variables
}
